{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "8eccda25_625076a0",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 14020
      },
      "writtenOn": "2024-07-17T19:56:26Z",
      "side": 1,
      "message": "Looks like the trybot failure is due to our friend TestManyCalls...",
      "revId": "115046185f100ed0176d78a13e4363c7be241684",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    }
  ]
}