{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "d277740b_5195d2d9",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 11500
      },
      "writtenOn": "2021-10-13T23:04:23Z",
      "side": 1,
      "message": "Trybot failure seems unrelated. I rebased and locally ./all.bash passes.\nCan we try running trybot again? (I think I don\u0027t have permission)",
      "revId": "459dbe2012c9a6ef2eebb34be10085402d23d91f",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    }
  ]
}