{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "857f12f9_84b54a2d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 64033
      },
      "writtenOn": "2024-02-06T12:29:09Z",
      "side": 1,
      "message": "I don\u0027t think the failure on LUCI was caused by this CL.",
      "revId": "4ab50edd34ba154d84eb44390a29bf182ad32eb2",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    }
  ]
}