{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "90c5750b_8a6eb06c",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 17092
      },
      "writtenOn": "2020-11-09T16:16:24Z",
      "side": 1,
      "message": "Sorry, I didn\u0027t finish reviewing this before going offline this week. Looks good.\n\nI think the x/tools failure is unrelated. I remember seeing a similar error a few weeks ago. Not sure if it\u0027s exactly the same.",
      "revId": "8472703d9ffe3bb4e5fd0bb4281675028dad8ca0",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    }
  ]
}